### ISSUE TITLE
Error: Command failed: "node" ace list:routes --json

### ISSUE THREAD

**Issue by RockyScube** [Julien-R44/adonis-vscode-extension#14] opened 2022-10-25 11:37 UTC
## Package version
0.8.0

## Node.js and npm version
16.14.2 & 8.5.0

Not able to see routes list, getting this error ***Error: Command failed: "node" ace list:routes --json***

**Comment by Julien-R44** [comment] 2022-10-29 11:03
When does this happen? When you open your workspace or when you try to list the routes via the command palette? 

If you try to run the command `node ace list:routes` manually I guess it works? 

Do you have several workspaces open in your editor?
Are you using a monorepo?

**Comment by Julien-R44** [comment] 2022-11-02 12:26
Might be a duplicate of #12. Closing for tracking in the other issue

**Closed by Julien-R44** 2022-11-02 12:26 UTC
