### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by iyashpal** [Julien-R44/adonis-vscode-extension#21] opened 2023-03-03 06:37 UTC
`TypeError: Cannot read properties of undefined (reading 'uri')` error pops up every time when I open a new project on vs code.

## Node.js and npm version
- Node v16.18.0
- Npm v9.3.1

![image](https://user-images.githubusercontent.com/19922707/222649180-2f9d1766-ae55-4a94-9949-588a81fe6f9e.png)

**Comment by Julien-R44** [comment] 2023-06-03 12:11
Duplicate of #12

**Closed by Julien-R44** 2023-06-03 12:11 UTC
